### 유저 상세 조회
GET http://localhost:8080/member/1
Accept: application/json

### 새로운 유저 생성
POST http://localhost:8080/member
Content-Type: application/json

{
  "name": "홍길동",
  "username": "honggd"
}

### 유저 정보 수정
PUT http://localhost:8080/member/11
Content-Type: application/json

{
  "name": "홍길순",
  "username": "testuser"
}

### 실패 케이스: 유저 생성 시 이름 누락
POST http://localhost:8080/member
Content-Type: application/json

{
  "username": "testuser"
}

### 실패 케이스: 유저 생성 시 username 누락
POST http://localhost:8080/member
Content-Type: application/json

{
  "name": "테스트"
}
